import json
import random
import uuid
from uuid import UUID

words = [
    ["Sneaky", "Wobbly", "Grumpy", "Dizzy", "Funky", "Squishy", "Clumsy", "Fancy", "Sleepy", "Bouncy", "Cranky",
     "Goofy", "Silly", "Jazzy", "Zany", "Wacky", "Quirky", "Nifty", "Perky", "Dorky", "Jiggly", "Wiggly", "Giggly",
     "Squiggly", "Snuggly", "Cuddly", "Bubbly", "Floppy", "Sloppy", "Choppy", "Droopy", "Loopy", "Poopy", "Goopy",
     "Lumpy", "Bumpy", "Dumpy", "Jumpy", "Stumpy", "Frumpy", "Grubby", "Rusty", "Dusty", "Musty", "Crusty", "Gusty",
     "Busty", "Trusty", "Fizzy", "Frizzy", "Tizzy", "Whizzy", "Bizzy", "Busy", "Fuzzy", "Snazzy", "Hazy", "Lazy",
     "Crazy", "Dazy", "Mazy", "Woozy", "Fluffy", "Stuffy", "Huffy", "Puffy", "Scruffy", "Snuffy", "Muffy", "Grungy",
     "Spongy", "Dingy", "Stringy", "Springy", "Clingy", "Stingy", "Creaky", "Squeaky", "Leaky", "Tweaky", "Cheeky",
     "Freaky", "Beaky", "Clunky", "Chunky", "Spunky", "Hunky", "Junky", "Punky", "Flunky", "Lanky", "Yanky", "Swanky",
     "Blanky", "Planky", "Shanky", "Tanky", "Shifty", "Thrifty", "Drifty", "Swifty", "Gifty", "Sifty", "Sketchy",
     "Stretchy", "Tetchy", "Fetchy", "Kvetchy", "Itchy", "Pitchy", "Sassy", "Classy", "Grassy", "Brassy", "Gassy",
     "Glassy", "Massy", "Trippy", "Hippy", "Dippy", "Zippy", "Nippy", "Sippy", "Chippy", "Scrawny", "Brawny", "Lawny",
     "Yawny", "Fawny", "Dawny", "Spawny", "Snooty", "Booty", "Rooty", "Sooty", "Tooty", "Fruity", "Hooty", "Bratty",
     "Chatty", "Fatty", "Natty", "Ratty", "Tatty", "Catty", "Snarky", "Sparky", "Barky", "Larky", "Marky", "Parky",
     "Sharky", "Plucky", "Ducky", "Lucky", "Mucky", "Ucky", "Yucky", "Chucky", "Snappy", "Happy", "Sappy", "Nappy",
     "Crappy", "Flappy", "Yappy", "Kooky", "Spooky", "Hooky", "Cooky", "Booky", "Looky", "Nooky", "Wonky", "Honky",
     "Donky", "Conky", "Bonky", "Tonky", "Zonky", "Dotty", "Potty", "Spotty", "Knotty", "Grotty", "Snotty", "Hotty",
     "Batty", "Patty", "Matty", "Hatty", "Bratsy", "Flatty", "Scatty", "Loony", "Moony", "Goony", "Spoony", "Croony",
     "Toony", "Noony", "Corny", "Horny", "Thorny", "Porny", "Forny", "Morny", "Borny", "Spacey", "Lacey", "Racey",
     "Pacey", "Facey", "Tracey", "Gracey", "Twitchy", "Witchy", "Glitchy", "Stitchy", "Ritchy", "Mitchy", "Hitchy",
     "Sniffly", "Sniffy", "Miffy", "Tiffy", "Piffy", "Riffy", "Iffy", "Swirly", "Twirly", "Whirly", "Curly", "Burly",
     "Surly", "Hurly", "Tingly", "Jingly", "Singly", "Dingly", "Mingly", "Ringly", "Wingly", "Rattly", "Tattly",
     "Battly", "Prattly", "Chattly", "Fattly", "Nattly", "Scribbly", "Dribbly", "Wibbly", "Jibbly", "Nibbly", "Gibbly"],
    [
        "Satya", "Sundar", "Mark", "Elon", "Jeff", "Tim", "Jensen", "Lisa",
        "Marc", "Michael", "Bill", "Larry", "Sergey", "Reed", "Susan", "Sheryl",
        "Ginni", "Safra", "Chuck", "Thomas", "Pat", "Frank", "Brian", "Aneel",
        "Amit", "Arvind", "Nikesh", "Hock", "Rajeev", "Anirudh", "Jayshree", "Diane",
        "Sam", "Dario", "Daniela", "Demis", "Shane", "Mustafa", "Greg", "Ilya",
        "Andrej", "Wojciech", "Noam", "Geoffrey", "Yann", "Andrew", "Fei", "Ian",
        "Morris", "Cristiano", "Gelsinger", "Rene", "Victor", "Lipbu", "Ajay",
        "Walden", "Toshiya", "Kiyoshi", "David", "Ming", "Rick", "Linus", "Hector", "Kelvin",
        "Adam", "Noah", "Kevin", "Stewart", "Linda", "Parag", "Evan", "Bobby",
        "Nathan", "Ben", "Emmett", "Daniel", "Nick", "Alex", "Drew", "Casey",
        "George", "Wendy", "Jay", "Sanjay", "Asaf", "Gil", "Yaniv", "Assaf",
        "Tomer", "Guy", "Udi", "Shlomo", "Avishai", "Rakesh", "Bipul", "Meir",
        "Patrick", "John", "Dan", "Max", "William", "Isabel", "Vlad", "Baiju",
        "Zach", "Henrique", "Anthony", "Pedro", "Nubank", "Nelson", "Nik", "Brett",
        "Andy", "Colin", "Doug", "Rishi", "Tony", "Dara", "Logan", "Melanie",
        "Jennifer", "Katrina", "Julie", "Sarah", "Steph", "Emily", "Hannah", "Tyler",
        "Aaron", "Dharmesh", "Godard", "Josh", "Zander", "Eric", "Sridhar",
        "Olivier", "Mikkel", "Per", "Carl", "Tien", "Paulo", "Renee", "Slater", "Tope",
        "Matthew", "Michelle", "Armon", "Mitchell", "Sid", "Parker", "Christian",
        "Edith", "Dylan", "Scott", "Jassy", "Werner", "Peter", "Adrian", "Kelsey", "Angie",
        "Dev", "Ali", "Eliot", "Igor", "Dwight", "Neha", "Monte", "Reynold",
        "Ion", "Matei", "Arsalan", "Naveen", "Vijay", "Suresh", "Prashant", "Raghu",
        "Nat", "Harj", "Eiso", "Kyle", "Abhinav", "Beyang", "Quinn", "Johannes",
        "Chris", "Brandon", "Tobi", "Harley", "Guillermo", "Mathias", "Sytse", "Oleg",
        "Glen", "Vivek", "Amir", "Jonathan", "Krishna", "Anne", "Elizabeth",
        "Atul", "Martin", "Neil", "Toby", "Mike", "Aneesh", "Shashank", "Tanay", "Rahul",
        "Sal", "Daphne", "Shaily", "Anant", "Nikhil", "Zvi", "Jose", "Jeremy",
        "Richard", "Ashwin", "Pankaj", "Shantanu", "Bhavin", "Ronnie", "Divya", "Karan",
        "Gabe", "Strauss", "Phil", "Don", "Amy", "Satoru", "Shigeru", "Hideo",
        "Hidetaka", "Yves", "Markus", "Hermen", "Ryan", "Jim", "Jade", "Tina",
        "Aicha", "Gill", "Clara", "Sebastian", "Dmitri", "Boris", "Marius",
        "Aurora", "Sterling", "Rod", "Bryan", "Raquel", "Helen", "Missy", "Kai", "Omar"
    ],
    [
        "stumbles", "wobbles", "bumbles", "fumbles", "tumbles",
        "trips", "slips", "flops", "plops", "drops",
        "splats", "spills", "tips", "topples", "lurches",
        "staggers", "teeters", "totters", "flails", "sprawls",
        "bonks", "clonks", "thuds", "thunks", "plunks",
        "splashes", "sloshes", "squishes", "squelches", "splatters",
        "dribbles", "drips", "leaks", "oozes", "seeps",
        "sneezes", "wheezes", "coughs", "hiccups", "burps",
        "giggles", "snickers", "chuckles", "cackles", "guffaws",
        "snorts", "snores", "yawns", "yodels", "warbles",
        "honks", "toots", "squeaks", "squeals", "shrieks",
        "waddles", "shuffles", "trudges", "plods", "lumbers",
        "skips", "hops", "bounces", "bounds", "prances",
        "twirls", "spins", "whirls", "swirls", "spirals",
        "wiggles", "jiggles", "waggles", "dangles", "sways",
        "flaps", "flutters", "flops", "frolics", "gallivants",
        "meanders", "wanders", "drifts", "loafs", "lounges",
        "dawdles", "dillydallies", "lollygags", "goofs", "clowns",
        "mucks", "bungles", "botches", "flubs", "blunders",
        "garbles", "mangles", "jumbles", "scrambles", "muddles",
        "confuses", "befuddles", "bewilders", "bamboozles", "flummoxes",
        "flusters", "frazzles", "rattles", "jangles", "clangs",
        "bangs", "clanks", "crashes", "smashes", "bashes",
        "whacks", "thwacks", "wallops", "clobbers", "conks",
        "bops", "bonks", "dings", "dongs", "gongs",
        "jingles", "tinkles", "clinks", "pinks", "plinks",
        "patters", "putters", "tinkers", "fiddles", "doodles",
        "scribbles", "scrawls", "scratches", "claws", "paws",
        "grabs", "snatches", "clutches", "grips", "grasps",
        "nabs", "pinches", "pokes", "prods", "jabs",
        "nudges", "bumps", "jostles", "elbows", "shoulders",
        "shoves", "pushes", "heaves", "hauls", "lugs",
        "drags", "tugs", "yanks", "jerks", "wrenches",
        "twists", "bends", "buckles", "crumples", "collapses",
        "sags", "droops", "wilts", "slouches", "slumps",
        "floofs", "poofs", "puffs", "huffs", "blows",
        "whiffs", "sniffs", "snuffles", "snorgles", "schnozzles",
        "gobbles", "guzzles", "gulps", "slurps", "chomps",
        "munches", "crunches", "gnaws", "nibbles", "pecks",
        "scarfs", "wolfs", "inhales", "devours", "demolishes",
        "snarfs", "noshes", "grazes", "gorges", "feasts",
        "belches", "barfs", "hurls", "upchucks", "regurgitates",
        "spews", "spouts", "gushes", "spurts", "sprays",
        "spritzes", "mists", "drizzles", "sprinkles", "spatters",
        "flicks", "flings", "tosses", "lobs", "chucks",
        "hurls", "launches", "catapults", "yeets", "boings",
        "ricochets", "careens", "zooms", "zips", "zings",
        "whizzes", "whooshes", "swooshes", "vrooms", "putters",
        "chugs", "sputters", "backfires", "konks", "stalls",
        "revs", "rumbles", "grumbles", "groans", "creaks",
        "squeaks", "grinds", "grates", "screeches", "scrapes",
        "rustles"
    ],
    [
        "the codebase",
        "the entire company",
        "so spectacularly",
        "everything—EVERYTHING",
        "through production logs",
        "the ethernet cable",
        "in merge hell",
        "their coffee mug",
        "both monitors frantically",
        "past code review",
        "onto some keyboard",
        "the deploy button",
        "Slack notifications endlessly",
        "through git blame",
        "all commit messages",
        "deprecated dependencies around",
        "under technical debt",
        "exceptions everywhere",
        "all the bandwidth",
        "over stack traces",
        "async promises together",
        "coffee on servers",
        "Docker containers wildly",
        "the build pipeline",
        "with CSS padding",
        "memory leaks daily",
        "the API documentation",
        "open DevTools furiously",
        "every standup meeting",
        "straight to prod",
        "tech debt around",
        "through code reviews",
        "impossible deadlines daily",
        "keyboard at bug",
        "unreviewed commits constantly",
        "with legacy code",
        "at compiler errors",
        "Stack Overflow answers",
        "database migrations spectacularly",
        "at merge conflicts",
        "expired certificates accidentally",
        "all cloud credits",
        "passive-aggressive PR comments",
        "whiteboard during design",
        "up technical jargon",
        "Twitter's infrastructure",
        "onto standby mode",
        "under sprint pressure",
        "ancient jQuery code",
        "deprecated npm packages",
        "their hot take",
        "through code review",
        "invalid JSON everywhere",
        "the loading spinner",
        "about memory leaks",
        "the API keys",
        "deprecated dependencies",
        "at unit tests",
        "the demo spectacularly",
        "production data accidentally",
        "the on-call rotation",
        "the Redis cache",
        "through tech debt",
        "off rate limits",
        "during the sprint",
        "into staging chaos",
        "past security checks",
        "the authentication flow",
        "at webpack errors",
        "on cloud costs",
        "the build system",
        "the deployment script",
        "malformed requests constantly",
        "main without testing",
        "the database migration",
        "through legacy code",
        "the error alerts",
        "the wrong endpoint",
        "through standup forever",
        "the entire cluster",
        "the load balancer",
        "all the bandwidth",
        "the technical debt",
        "the environment variables",
        "the Docker container",
        "the microservice mesh",
        "the SSH tunnel",
        "through PRs unreviewed",
        "the customer demo",
        "the network cable",
        "illegible documentation",
        "the notification bell",
        "open the terminal",
        "the monitoring dashboard",
        "through code freeze",
        "the cursor aimlessly",
        "the config file",
        "null pointer exceptions",
        "dev and prod",
        "to production deploy",
        "the WebSocket connection",
        "past the linter",
        "past code coverage",
        "onto the main branch",
        "through the firewall",
        "the EC2 instances",
        "into callback hell",
        "the feature toggle",
        "breaking changes live",
        "the release candidate",
        "at CORS errors",
        "the build horn",
        "every retrospective meeting",
        "the Docker daemon",
        "the state management",
        "up spaghetti code",
        "on the keyboard",
        "all the RAM",
        "the health check",
        "the CDN rules",
        "through daily standup",
        "the Jira notifications",
        "the schema migration",
        "credentials into GitHub",
        "at regex patterns",
        "technical debt everywhere",
        "through the firewall",
        "on the hotfix",
        "past the linter",
        "the build cache",
        "the backlog ruthlessly",
        "at test coverage",
        "over authentication checks",
        "through the postmortem",
        "the executive demo",
        "during the incident",
        "every single dependency",
        "logs across Datadog",
        "the rollback procedure",
        "mock data everywhere",
        "the Kubernetes pod",
        "during code freeze",
        "all available threads",
        "the connection pool",
        "the SSL handshake",
        "without smoke tests",
        "the load balancer",
        "into prod accidentally",
        "the OAuth flow",
        "through sprint planning",
        "the Git history",
        "the mouse frantically",
        "the deployación completa",
        "the servidor rosa",
        "through el sprint",
        "das Kubernetes manifest",
        "the arquitectura elegante",
        "el certificado SSL",
        "die database verbindung",
        "malformed JSONs everywhere",
        "the microservicios instantly",
        "das build pipeline",
        "over la taula",
        "the legacy código",
        "during les Falles",
        "el merge conflict",
        "credentials ins repository",
        "through tech deuda",
        "sin smoke tests",
        "die authentication tokens",
        "logs por todas partes",
        "down la escalivada",
        "invalid XMLs constantly",
        "at webpack Warnungen",
        "into producción directamente",
        "during la Mercè",
        "over das dependency hell",
        "el feature flag",
        "at unit Prüfungen",
        "die cloud infraestructura",
        "with spaghetti código",
        "onto el canal principal",
        "through das backlog",
        "the Docker contenedor",
        "at npm Fehler",
        "la configuración incorrecta",
        "el health check",
        "with el sisteme obsolet",
        "through die retrospektive",
        "over las dependencias rotas",
        "incompatible package Versionen",
        "down pa amb tomàquet",
        "the customer demostración",
        "under technical Schuld",
        "el mismo bug",
        "through die Kubernetes pods",
        "at CORS errores",
        "over authentication Schranken",
        "las pruebas unitarias",
        "through el deploy manual",
        "das terminal nervös",
        "all available memòria",
        "la migración completa",
        "into die Produktionsumgebung",
        "el cable de xarxa",
        "bugs por el codebase",
        "das entire Cluster",
        "through legacy Kode",
        "stack traces constantemente",
        "during el code freeze",
        "at la butifarra",
        "ancient dependencias everywhere",
        "at TypeScript anys",
        "die technical Verantwortung",
        "the alarm campana",
        "through el commit history",
        "the OAuth fluxe",
        "café sobre el teclat",
        "through das morning meeting",
        "up la base de dades",
        "on everyone's Nerven",
        "the hotfix directo",
        "into producció sense testejar",
        "las API conventions",
        "das monitoring dashboard",
        "deprecated biblioteques around",
        "at el teclado lentament",
        "das entire Schema",
        "up die server Lichter",
        "invalid JSONs constantment",
        "onto el main branch",
        "at code Kommentare",
        "Twitter's entire infraestructura",
        "through las pull requests",
        "all the CPU recursos",
        "past security Kontrollen",
        "at quarterly Ergebnisse",
        "ancient código everywhere",
        "at das error handling",
        "the load Balanceador",
        "exceptions por doquier",
        "null pointer Ausnahmen",
        "through el sprint planning",
        "across multiple repositoris",
        "at webpack Warnungen",
        "the error Glocken",
        "every retrospectiva meeting",
        "die deployment Pipeline",
        "during la diada",
        "requests at el servidor",
        "with spaghetti Architektur",
        "technical deute eternament",
        "el casteller humà",
        "invalid SQL constantemente",
        "through das monitoring",
        "into callback Inferno"
    ]
]


def generate(uuid_input: UUID | str, just_name: bool = True) -> str:
    """
    Generate a named UUID from a UUID object.

    Args:
        uuid_input: UUID object

    Returns:
        String with first 4 bytes replaced by words + rest of UUID
        (e.g., "sneaky Mark stumbles through-e29b-41d4-a716-446655440000")
    """
    # Assert all word lists have exactly 256 entries
    if isinstance(uuid_input, str):
        # can raise error. user responsibility
        uuid_input = UUID(uuid_input)
    for idx, word_list in enumerate(words):
        assert len(word_list) == 256, f"Word list {idx} has {len(word_list)} entries, expected 256"

    # Get the first 4 bytes from the UUID bytes
    uuid_bytes = uuid_input.bytes
    first_4_bytes = uuid_bytes[:4]

    # Generate named part using the first 4 bytes as indices
    selected_words = []
    for idx, byte_value in enumerate(first_4_bytes):
        selected_words.append(words[idx][byte_value])

    # Get the rest of the UUID (everything after the first 8 hex chars)
    uuid_str = str(uuid_input)
    rest_of_uuid = uuid_str[9:]  # Skip first 8 chars and the hyphen

    # Return named part + rest of UUID
    named_part = " ".join(selected_words)
    if just_name:
        return named_part

    return f"{named_part}-{rest_of_uuid}"

if __name__ == "__main__":
    from uuid import uuid4
    u_ = uuid4()
    print(u_)
    print(generate(u_))
    print(generate(u_, False))